import DeleteIndicator, {
  DELETE_INDICATOR_HEIGHT,
  DELETE_INDICATOR_WIDTH,
  DELETE_INDICATOR_X,
  DELETE_INDICATOR_Y,
} from "./DeleteIndicator";

export {
  DELETE_INDICATOR_HEIGHT,
  DELETE_INDICATOR_WIDTH,
  DELETE_INDICATOR_X,
  DELETE_INDICATOR_Y,
};
export default DeleteIndicator;
